### PR TITLE
add a new location for prayer information and add a hotkey for adding time based on stomps

### PR DESCRIPTION
**Pull request by superev**

### CODE REVIEW

**Comment by Loze-Put** [comment]
I'll take a look at it.

**Comment by superev** [comment]
thanks for the update was a bit worried you had disappeared 😅

**Comment by Ethan-Vann** [comment]
any further update on this?

**Comment by superev** [comment]
any further update on this?

**Comment by Loze-Put** [comment]
Hi, thanks for your contribution. I have taken a look at your PR and have some feedback.

First of all I noticed some inconsistent code styling. My code had that as well, so I cleaned it up a bit. You can find some information on automated tools in the [RuneLite docs](https://github.com/runelite/runelite/wiki/Code-Conventions). The codestyle files are in the main directory.

The keybinding for trampling now prevents using that key for other things such as typing text. I think this is fine during the fight, but it might get annoying in between fights. This could be fixed by checking the active state of the plugin to the handler of the key bind.

The overlay feature has a similair issue. The overlay still shows after stopping the timer. I think this should remove the overlay. Another suggestion is to remove the overlay after switching tabs away from the prayer book. The overlay currently shows on any other tab as well.

I'm also in doubt if the overlay feature would be allowed or if it is in conflict with the Jagex third party client statement. For now I'm willing to let the RuneLite team be the judge of that.

**Comment by superev** [comment]
Thanks for the response again. I will implement RL checkstyle and update pr when I'm able. As for the rules I think its fine as they are currently being interpreted. My commits don't add any new info or tracking just a new location for information which I don't think should affect the legality.

**Pull request closed without merging**
